### ISSUE TITLE
Could not build project from CLI

### ISSUE THREAD

**Issue by vbauer** [nshmura/SnappySmoothScroller#1]
Hello I faced with the following problem: https://raw.githubusercontent.com/android-arsenal/apk16/master/3909/log.txt

Is it possible to allow to build project without any extra changes in property files?

**Comment by nshmura** [comment]
Hi @vbauer,
Key store file is required for the release build.
Please comment out the below line.
https://github.com/nshmura/SnappySmoothScroller/blob/a8f2e73630f3b0224ebd99df48a6fce5d0c479e1/demo/build.gradle#L28

**Comment by vbauer** [comment]
Is it possible to move release into separate property/profile to allow `./gradlew build` for development purpose?

**Comment by nshmura** [comment]
ok! I fixed master branch https://github.com/nshmura/SnappySmoothScroller/commit/5d2f9fb9d83c39a699d5994bd10ce99b8b9d93ff
This problem should be solved.

**Comment by vbauer** [comment]
Thank you very much!
