### ISSUE TITLE
What exactly is seek duration?

### ISSUE THREAD

**Issue by AlanCPSC** [nshmura/SnappySmoothScroller#2]
Hi, thanks for writing this library. I am a bit concerned about the lack of documentation.

What exactly is `setSeekDuration`?

**Comment by AlanCPSC** [comment]
I realized I don't really care.

**Comment by nshmura** [comment]
@AlanCPSC Sorry for late response.  
`setSeekDuration` means duration time of scrolling.
But it is not exact time, If layoutManager can not detect the distance to target view.
